name: generate animation

on:
  # Spouští se automaticky každých 24 hodin
  schedule:
    - cron: "0 0 * * *" 
  
  # Umožňuje ruční spuštění workflow kdykoli
  workflow_dispatch:
  
  # Spouští se při každém pushi do větve master
  push:
    branches:
      - master

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Generuje hadí hru z grafu příspěvků uživatele, výstupem je svg animace
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3.3.0
        with:
          github_user_name: No898
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Pushuje obsah <build_dir> do cílové větve
      # Obsah bude dostupný na https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> nebo jako GitHub Page
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4.1.0
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
